Repository accordproject/markdown-transform, pull requests merged in 2019-10, with the labels that each got.

#38 fix(README): broken link - I37
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#36 docs(README): add downloads badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#33 docs(CONTRIBUTING): init contributor doc - I16
  CONTRIBUTING.md
Labels: 0.20-alpha, Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#32 docs(DEVELOPERS): init developer doc - I17
  DEVELOPERS.md
Labels: 0.20-alpha, Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#31 docs(*): sync Accord Project documents - I18
  CHARTER.md
  README.md
Labels: 0.20-alpha, Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#40 fix(package): jsome dependency - I29
  packages/markdown-cli/package.json
  packages/markdown-common/package.json
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#48 fix(test): variables from blocks to inlines
  package-lock.json
  packages/markdown-cli/test/data/acceptance-slate.json
  packages/markdown-slate/src/SlateTransformer.test.js
  packages/markdown-slate/src/ToSlateVisitor.js
  packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
  packages/markdown-slate/test/data/acceptance.json
Labels: Type: Bug 🐛

#50 fix(slate): move text value from data to nodes
  packages/markdown-cli/test/data/acceptance-slate.json
  packages/markdown-slate/src/SlateTransformer.test.js
  packages/markdown-slate/src/ToSlateVisitor.js
  packages/markdown-slate/src/__snapshots__/SlateTransformer.test.js.snap
  packages/markdown-slate/test/data/acceptance.json
Labels: Type: Bug 🐛

#56 docs(README): add license badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#60 docs(README): add slack and build badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#54 doc(README): centering title and badges
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#78 feat(docs): add ecosystem table
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#80 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#97 fix(README): grammar
  README.md
Labels: Difficulty: Starter, Hacktoberfest
